@startmindmap
* GraphQL

** GraphQL AspNet Core

***_ Query definition 
***_ Schema definition

*** Type definition

****_ Scalar Type
****_ Complex Type

*** Configure Startup

****_ Exception stack trace
****_ Middleware

*** Web Client

****_ Altair
@endmindmap