@startmindmap
* GraphQL .Net

** GraphQL AspNet Core

***_ Query definition 
***_ Schema definition
***_ EF Core integration

*** Type definition

****_ Scalar Type
****_ Complex Type

*** Configure Startup

****_ Exception stack trace
****_ Middleware

***[#lightgrey] Web Client

****_ Altair
@endmindmap