@startmindmap
*[#LightBlue] Wavenet Formation
--[#Lightgreen] Services
---_ Formation débutant
---_ Formation d'entreprise
**[#Lightgreen] Canaux
***_ Intranet
***_ Auditoire
**[#Lightgreen] Format
***_ eBook / Documentation
***_ Tech-Tips
***_ Support Formation
@endmindmap