@startmindmap
*[#LightBlue] Wavenet Formation
--[#MistyRose] Services
---[#Lightgreen] Formation débutant
---[#Lightgreen] Formation d'entreprise
---[#Orange] Domaine d'expertise
---[#Orange] Conférence
**[#MistyRose] Canaux
***[#Lightgreen] Intranet
***[#Lightgreen] Auditoire
***[#Orange] Youtube
***[#Orange] LinkedIn
***[#Orange] Portail Web
**[#MistyRose] Format
***[#Lightgreen] eBook (pdf)
***[#Lightgreen] Tech-Tips (Video)
***[#Lightgreen] Support Formation (Slide)
***[#Orange] Syllabus (Markdown)
***[#Orange] Deep Dive (Video)
***[#Orange] Radio IT (Podcast)
***[#Orange] POC (Github)
***[#Orange] HowTo (Video)
@endmindmap